default: &default
  url: redis://127.0.0.1:6379/0
  timeout: 5
  reconnect_attempts: 3

development:
  <<: *default

test:
  <<: *default
  url: redis://127.0.0.1:6379/1

production:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL", "redis://127.0.0.1:6379/0") %>
