CREATE_NEW_TILE_NAMES = {
    goals: 'Launch Quality Measure Goal',
    announcements: 'Launch Announcement',
    health_events: 'Launch New Health Event',
    health_educations: 'Launch New Health Education Goal',
    compliances: 'Launch New Complaince Plan',
    member_feedbacks: 'Launch New Feedback / Surveys',
    timely_recovery_goals: 'Launch QI/MCAS Measure Strategy',
    overseers: 'New Api Access Users Setup',
    custom_templates: 'New Template',
    care_managements: 'New Care Management',
    chronic_condition_management_goals: 'New Chronic Condition Management Goal',
}

TITLE = {
  Goal: 'Action Plans',
  HealthEvent: 'Action Plans',
  HealthEducation: 'Action Plans',
  TimelyRecoveryGoal: 'Action Plans',
  Announcement: 'Announcements',
  MemberFeedback: 'Feedbacks',
  Compliance: 'Feedbacks'
}
TILE_COLORS = ['success', 'warning', 'danger', 'primary', 'secondary', 'info', 'dark']

CUSTOM_TEMPLATE__HASH = {
  'Goal': 0,
  'Announcement': 1,
  'HealthEvent': 2,
  'HealthEducation': 3,
  'MemberFeedback': 4,
  'Complaince': 5,
  'CareManagement': 6,
  'ChronicConditionManagementGoal': 7
}

ICONS_HASH = {
  'Well Child Care': 'fa fa-heartbeat',
  'ED Follow Ups': 'fa fa-first-aid',
  'Counseling': 'fa fa-users',
  'General': 'fa fa-info-circle',
  'Eligibility & Benefits': 'fa fa-dollar-sign',
  'Service/Care Providers': 'fa fa-user-md',
  'Care Utilization': 'fa fa-chart-bar',
  'Care Access': 'fa fa-map-marker',
  'Member Disclosures': 'fa fa-lock',
  'Nutrition': 'fa fa-carrot',
  'Physical/Mental Health': 'fa fa-brain',
  'Preventive Care': 'fa fa-shield-virus',
  'Screenings': 'fa fa-clipboard-check',
  'Immunizations': 'fa fa-syringe',
  'Care': 'fa fa-heart',
  'Service': 'fa fa-wrench',
  'Member Forms': 'fa fa-file',
  'CAPHS': 'fa fa-home',
  'Health Plan': 'fa fa-heartbeat',
  'Care Barriers': 'fa fa-ban',
  'Condition Management': 'fa fa-stethoscope',
  'Follow Up Care': 'fa fa-clock',
  'Medication Refill': 'fa fa-pills',
  'Program Enrollment': 'fa fa-check-circle',
  'Launch Quality Measure Goal': 'fa fa-bullseye',
  'Launch Announcement': 'fa fa-bullhorn',
  'Launch New Health Event': 'fa fa-calendar-check',
  'Launch New Health Education Goal': 'fa fa-book-open',
  'Launch New Complaince Plan': 'fa fa-check-circle',
  'Launch New Feedback / Surveys': 'fa fa-comment',
  'Launch QI/MCAS Measure Strategy': 'fa fa-chart-line',
  'New Api Access Users Setup': 'fa fa-user-plus',
  'New Template': 'fa fa-clipboard-list',
  'Quality Measure Goals': 'fa fa-bullseye',
  'Condition Management Goals': 'fa fa-stethoscope',
  'Chronic Management Dashboard': 'fa fa-chart-line',
  'Transition Care Management': 'fa fa-hand-pointer',
  'Enhance Care Management': 'fa fa-chart-line',
  'Long Term Care': 'fa fa-calendar-alt',
  'Diabetic': 'fa fa-medkit',
  'Hypertension (High Blood Pressure)': 'fa fa-heartbeat',
  'Asthma': 'fa fa-lungs',
  'Cardiovascular Disease': 'fa fa-heart',
  'Chronic Obstructive Pulmonary Disease (COPD)': 'fa fa-lungs-virus',
  'Chronic Kidney Disease': 'fa fa-filter',
  'Timely Interventions Goals': 'fa fa-clock',
  'Condition Management Goals': 'fa fa-stethoscope',
  'Care Management': 'fa fa-heart',
  'Health Education': 'fa fa-book-open',
  'Feedback / Surveys': 'fa fa-comment',
  'Announcements': 'fa fa-bullhorn',
  'Health Event Goals': 'fa fa-calendar-check',
  'Compliance Goals': 'fa fa-check-circle',
  'Member Engagement': 'fa fa-handshake',
  'Chronic Management': 'fa fa-chart-line',
  'New Care Management': 'fa fa-plus-circle',
  'New Chronic Condition Management Goal': 'fa fa-plus-circle',
  "Population Health Management": "fa fa-users",
  "Complex Care Management": "fa fa-hands-helping",
  "Case Management": "fa fa-clipboard-list",
  "Chronic Disease Management": "fa fa-heartbeat",
  "Transitional Care Management": "fa fa-exchange-alt",
  "Patient Safety": "fa fa-shield-alt",
  "Member Services": "fa fa-user-friends",
  "Health Equity": "fa fa-balance-scale",
  "Referral Completion": "fa fa-check-circle"
}.with_indifferent_access
