# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.4'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '~> 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
end


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # help to kill N+1 queries and unused eager loading. (https://github.com/flyerhzm/bullet)
  gem 'bullet'
  # Ruby fast debugger - base + CLI (https://github.com/deivid-rodriguez/byebug)
  # Capybara aims to simplify the process of integration testing Rack applications, such as Rails, Sinatra or Merb (https://github.com/teamcapybara/capybara)
  # Autoload dotenv in Rails. (https://github.com/bkeepers/dotenv)
  # gem 'dotenv-rails'
  # factory_bot_rails provides integration between factory_bot and rails 5.0 or newer (https://github.com/thoughtbot/factory_bot_rails)
  gem 'factory_bot_rails'
  # Easily generate fake data (https://github.com/faker-ruby/faker)
  # gem 'faker', git: 'https://github.com/faker-ruby/faker.git'
  # Launchy is helper class for launching cross-platform applications in a fire and forget manner. (https://github.com/copiousfreetime/launchy)
  # gem 'launchy'
  # Run Test::Unit / RSpec / Cucumber / Spinach in parallel (https://github.com/grosser/parallel_tests)
  # gem 'parallel_tests'
  # Extracting `assigns` and `assert_template` from ActionDispatch. (https://github.com/rails/rails-controller-testing)
  gem 'rails-controller-testing'
  # RSpec for Rails (https://github.com/rspec/rspec-rails)
  gem 'rspec-rails'
  # Context framework extracted from Shoulda (http://thoughtbot.com/community/)
  gem 'shoulda-context'
  # Simple one-liner tests for common Rails functionality (https://matchers.shoulda.io/)
  gem 'shoulda-matchers'
  # Code coverage for Ruby (https://github.com/simplecov-ruby/simplecov)
  gem 'simplecov'
  # SimpleCov Cobertura Formatter (https://github.com/dashingrocket/simplecov-cobertura)
  gem 'simplecov-cobertura'
end



# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'devise'
gem 'devise_token_auth'
gem 'pry'
gem 'rails_admin', '~> 2.1'
gem 'sucker_punch', '~> 2.0'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'jquery-rails'
gem 'rack-cors', require: 'rack/cors'
gem 'remotipart', '~> 1.2'
gem 'will_paginate', '~> 3.3'

gem 'cancancan'
gem 'faker'
gem 'fcm'
gem 'lol_dba'
gem 'roo'
gem 'rubocop', '~> 1.50.2'
